### ISSUE TITLE
The endpoint /user/list/samples should return a unique list with all the samples. Inside each row 3 extra fields have to be added: the user is allowed to edit the sample, the user is allowed to publish the sample, the owner of the sample

### ISSUE THREAD

**Issue by adriaalcala** [biocom-uib/halodb-api#17]

**Comment by perep** [comment]
Done
It also returns the access mode, and the origin of the sample (is public, is owned by the user, is shared by another user, or by a group)

**Comment by adriaalcala** [comment]
I checked and looks like these fields are not returned when the user is not logged in. Besides this, could you send me the values instead of the references? For example, for the owner you are sending me the user id, could you send me the username or the email?

Besides this, if the user is logged in, the API returns a 500.

**Comment by perep** [comment]
Partially fixed.

Working on it

**Comment by perep** [comment]
The field that are an index to some supplementary table are replaced by the corresponding description.

Pending:

    Do the same with user id, experiment id and the tables (salinity, temperature and ph)

ATTENTION: DO NOT FILL the fields completeness, contamination, ggcm, sals
