### ISSUE TITLE
Create an endpoint to publish a sample. Given a logged user and a sampleId, publish the sample if the user is allowed to do it

### ISSUE THREAD

**Issue by adriaalcala** [biocom-uib/halodb-api#20]

**Comment by perep** [comment]
Done
https://biocom.uib.es/halodb/upload/sample/

the sample_id is generated automatically.

the user_id if forced to the value obtained from the credentials
the files are not used, they must be updated after the creation (via https://biocom.uib.es/halodb/upload/sample/<sample_id>/<input_type> )
the date fields are generated automatically.
the field is_public is not considered (the sample is private until is explicitly made public)

**Comment by adriaalcala** [comment]
This endpoint is to upload the data, I need an endpoint to use once the data is already uploaded and the user wants to make his sample public.

**Comment by perep** [comment]
Fixed

https://biocom.uib.es/halodb/share/public/<int:sample_id>
