### ISSUE TITLE
Create an endpoint that given a sampleId and a file type, returns the file if the user who makes the request is allowed to get that file

### ISSUE THREAD

**Issue by adriaalcala** [biocom-uib/halodb-api#21]

**Comment by perep** [comment]
Done
https://biocom.uib.es/halodb/query/sample/<sample_id>/<input_type>

input_type can be one of 

- rreads
- treads
- assembled
- pgenes

**Comment by adriaalcala** [comment]
Looks like these endpoints are checking if the user that makes the request is the owner, and should check if the user has access to the sample. Besides this, it should work for non-authorized user if the sample is public.

**Comment by perep** [comment]
Fixed
